POST http://localhost:3003/api/blogs/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer 


{
  "title": "Testing title",
  "author": "Testing name",
  "url": "http://testing.com",
  "likes": 0
}

###
POST http://localhost:3003/api/blogs/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer 


{
  "title": "Testing title",
  "author": "Testing name",
  "url": "http://testing.com",
  "likes": 0
}
