DELETE http://localhost:3001/api/notes/6a0f2656834fd6b3b2772e7e HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjZhMGYyNDU4ODM0ZmQ2YjNiMjc3MmU3OSIsImlhdCI6MTc3OTM3NzQ0OSwiZXhwIjoxNzc5MzgxMDQ5fQ.M36MwsN2wwCHHwhDHC8YXZVxIyjFKBx0q_acW8_vPTI

